# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0004_auto_20170721_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.User'),
        ),
    ]
